#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-

require "bundler/setup"

require "performant/utilities/task"
require "performant/utilities/histogram"

class Analyzer < Performant::Utilities::Task

  option "b", "buckets", default: 24

  def run
    lines = ARGF.readlines
    tds = lines.map { |line| line.split(",").map { |s| s.to_i } }

    h = Performant::Utilities::Histogram.new buckets: buckets
    b = h.process(tds.map(&:first))
    b.each_with_index { |n,i| printf "%i\t%i\n", i, n }
  end

end

Analyzer.parse(ARGV).run if __FILE__ == $0
