#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-

require "bundler/setup"

require "performant"
require "thor"

class Sampler < Thor

  desc "sample", "run the sampler"

  method_option :environment,  alias: "-e", default: "development"
  method_option :config,       alias: "-c", default: File.expand_path( "../example.yml", __FILE__ )
  method_option :jobs,         alias: "-j", type: :array, default: [ "stress", "fake" ]

  def sample
    Performant::Configuration.load! src: options.config, env: options.environment
    Performant.sampler(options.jobs).run
  end
end

Sampler.start if __FILE__ == $0
