#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-

require "bundler/setup"

require "performant"
require "thor"

class Sampler < Thor

  desc "run", "run the sampler"

  method_options :environment,  alias: "-e", default: "development"
  method_options :config,       alias: "-c", default: File.expand_path( "../example.yml", __FILE__ )
  method_options :jobs,         alias: "-j", type: :array, default: [ "stress", "fake" ]

  def run
    Performant::Configuration.load! src: options.config, env: options.environment

    sampler     = Performant.sampler
    sec_samples = Hash.new { { jobs: 0, busy: 0, work: 0 } }

    sampler.loop_until_false do

      puts Time.now
      options.jobs.each do |job|

        storage     = Performant.storage(job)
        last_sample = sec_samples[job]
        now_sample  = storage.robustly { storage.tick! }
        diff        = sampler.diff( now_sample, last_sample )
        puts diff.merge( job: job ).inspect

        sec_samples[job] = now_sample
      end
      true
    end
  end
end

Sampler.start if __FILE__ == $0
